### PR TITLE
fix(postman): introduce support for v2.0.0 auth object

### LINKED ISSUE #250: Postman: Converter fails to handle v2.0.0 request auth
### Description

Converting of v2.0.0 collection to HAR fails at the request auth handling. 

Here it is required to improve converter to handle v2.0.0 postman collection auth object scheme.

### Steps to reproduce

Pass the `my-schema.yaml` (see below) to the `postman2har` as follows:

```ts
import { postman2har } from '@har-sdk/postman';
import { readFile } from 'fs';
import { promisify } from 'util';
import { load } from 'js-yaml';

const content = await promisify(readFile)(
  './my-schema.yaml',
  'utf8'
);

const result = postman2har(load(content) as Postman.Document);
```

<details>
<summary>my-schema.yaml</summary>

```yaml
info:
  name: Auth
  schema: https://schema.getpostman.com/json/collection/v2.0.0/collection.json
item:
  - name: users
    item:
      - name: Users
        request:
          auth:
            type: bearer
            bearer:
              token: token-value
          method: GET
          header:
            - key: Accept
              value: application/json
          url: '{{baseUrl}}/users'
        response:
          - name: Success
            originalRequest:
              method: GET
              header:
                - key: Accept
                  value: application/json
                - key: Authorization
                  value: Bearer <token>
                  description: 'Added as a part of security scheme: bearer'
              url: '{{baseUrl}}/user'
            status: OK
            code: 200
            header:
              - key: Content-Type
                value: application/json
            cookie: []
            body: |-
              {
               "username": "<string>",
               "name": "<string>" 
              }
variable:
  - key: baseUrl
    value: https://example.com/api/v1
```
</details>

### Actual result

Error appears:

```
j.map is not a function
```

### Expected result

Conversion performed correctly, `auth` token value applied.

```json
[
  {
    "bodySize": -1,
    "cookies": [],
    "headers": [
      {
        "name": "Accept",
        "value": "application/json"
      },
      {
        "name": "authorization",
        "value": "Bearer token-value"
      }
    ],
    "headersSize": -1,
    "httpVersion": "HTTP/1.1",
    "method": "GET",
    "queryString": [],
    "url": "https://example.com/api/v1/users"
  }
]
```

### PR DESCRIPTION
**Pull request by ostridm**
fixes #250

### CODE REVIEW

File: packages/postman/src/converter/DefaultConverter.ts [hunk 1]
```diff
@@ -150,6 +146,23 @@ export class DefaultConverter implements Converter {
...
+
+    return !params
+      ? params
+      : Array.isArray(params)
+      ? Object.fromEntries(
+          params.map((val: Postman.Variable) =>
+            [val.key, val.value].map(String)
+          )
+        )
+      : params;
```
Comment (derevnjuk) [inline packages/postman/src/converter/DefaultConverter.ts:163]: Overcomplicated 

```suggestion
    return Array.isArray(params)
      ? Object.fromEntries(
          params.map((val: Postman.Variable) =>
            [val.key, val.value].map(String)
          )
        )
      : params;
```

**Review by derevnjuk — DISMISSED** [review]

**Review by derevnjuk — APPROVED** [review]
