### PR TITLE
fix(validator): property names in custom error messages

### LINKED ISSUE #50: Better wording for humanized error messages
Implement changes to improve intelligibility of error messages for the end users (details are at internal Confluence page)

### PR DESCRIPTION
**Pull request by pmstss**
fixes #50

### CODE REVIEW

File: packages/validator/src/humanizer/formatters/CustomErrorMessageFormatter.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+  public format(error: ErrorObject<'errorMessage'>): string {
+    if (error.keyword !== 'errorMessage') {
+      return;
+    }
+
+    const propName = WordingHelper.extractPropertyName(error.instancePath);
+
+    return error.message.replace(
+      /^The property must/,
+      `The property \`${propName}\` must`
```
Comment (derevnjuk) [inline packages/validator/src/humanizer/formatters/CustomErrorMessageFormatter.ts:15]: Why don't use relative JSON-pointer directly in schemas? https://github.com/ajv-validator/ajv-errors#using-property-names-in-error-messages

Comment (pmstss) [reply packages/validator/src/humanizer/formatters/CustomErrorMessageFormatter.ts:15]: thanks, was not aware of that `ajv-errors` possibility, but can't get it working for our case. seems `errorMessage` should be inside [`properties/some_prop`](https://github.com/ajv-validator/ajv-errors/blob/7efe8c29c3ea461eef29335e0199742dbc18e791/spec/object.spec.ts#L74). Trying to apply it [here ](https://github.com/NeuraLegion/har-sdk/blob/a7f1114e8d9dd2337a5be13e5408e6fc2b08f9e5/packages/validator/src/schemas/openapi/v3.0.0.json#L1006)leads to:
- `${0#}` -> exception `Cannot access property/index 0 levels up, current level is 0`
- `${/#}` -> `undefined`

Comment (derevnjuk) [reply packages/validator/src/humanizer/formatters/CustomErrorMessageFormatter.ts:15]: It looks like you are right 👍🏾

**Review by derevnjuk — APPROVED** [review]
