### PR TITLE
fix(validator): cast types while using substitution variables

### LINKED ISSUE #66: TypeError on substitution in the `Replacer`
```
[2021-12-06T19:19:14.504] [ERROR] [TSED] - Error while capturing the HAR: TypeError: this.value.replace is not a function
at l.replace (/opt/services/node_modules/@har-sdk/postman/src/parser/Replacer.ts:22:29)
at c.parse (/opt/services/node_modules/@har-sdk/postman/src/parser/EnvVariableParser.ts:18:27)
at d.apiKeyAuth (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:270:21)
at d.authRequest (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:125:14)
at d.convertRequest (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:101:14)
at reduce (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:56:51)
at Array.reduce (<anonymous>)
at d.traverse (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:48:24)
at reduce (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:53:36)
at Array.reduce (<anonymous>)
at d.traverse (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:48:24)
at reduce (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:53:36)
at Array.reduce (<anonymous>)
```

### PR DESCRIPTION
**Pull request by derevnjuk**
closes #66

### CODE REVIEW

File: packages/postman/src/converter/DefaultConverter.ts [hunk 1]
```diff
@@ -250,20 +231,11 @@ export class DefaultConverter implements Converter {
...
-
+    const parser = this.parserFactory.createEnvVariableParser(variables);
     const target: AuthLocation =
-      AuthLocation[(options.addTokenTo ?? 'header').toUpperCase()];
-
-    const idx: number = request[target].findIndex(
-      (x: QueryString | Header) =>
-        x.name.toLowerCase() === options.key.toLowerCase()
-    );
+      AuthLocation[(options.in ?? 'header').toUpperCase()];
```
Comment (pmstss) [inline packages/postman/src/converter/DefaultConverter.ts:236]: is it intended fix/change - `addTokenTo` -> `in`?

Comment (derevnjuk) [reply packages/postman/src/converter/DefaultConverter.ts:236]: Yeah, it must be `in` for the `apikey`. `addTokenTo` can be used only in the terms of `oauth2`

**Review by pmstss — APPROVED** [review]
