### PR TITLE
fix(validator): better humanized messages for array targets

### LINKED ISSUE #50: Better wording for humanized error messages
Implement changes to improve intelligibility of error messages for the end users (details are at internal Confluence page)

### PR DESCRIPTION
**Pull request by pmstss**
fixes #50

### CODE REVIEW

File: packages/validator/src/humanizer/formatters/ArrayFormatter.ts [hunk 1]
```diff
@@ -3,24 +3,26 @@ import { WordingHelper } from './WordingHelper';
 import { ErrorObject } from 'ajv';
 
 export class ArrayFormatter implements Formatter {
+  public supportedKeywords = ['maxItems', 'minItems', 'uniqueItems'];
```
Comment (derevnjuk) [inline packages/validator/src/humanizer/formatters/ArrayFormatter.ts:6]:
```suggestion
  private readonly supportedKeywords: ReadonlySet<string> = new Set(['maxItems', 'minItems', 'uniqueItems']);
```

File: packages/validator/src/humanizer/ErrorHumanizer.ts [hunk 2]
```diff
@@ -41,15 +41,12 @@ export class ErrorHumanizer {
...
-      ''
-    );
-
-    if (!message) {
-      message = error.message;
-    }
+    const message =
+      this.formatters
+        .find((formatter) =>
+          formatter.supportedKeywords.includes(error.keyword)
```
Comment (derevnjuk) [inline packages/validator/src/humanizer/ErrorHumanizer.ts:47]: Let's extract this as a separate method in `formatter`
```suggestion
          formatter.canProcessKeyword(error.keyword)
```

File: packages/validator/src/humanizer/formatters/WordingHelper.ts [hunk 3]
```diff
@@ -19,10 +19,28 @@ export class WordingHelper {
...
+      ? `The element at index ${index} in the array \`${name}\``
+      : `The property \`${name}\``;
+  }
+
+  private static extractTarget(jsonPointer: string): {
+    name: string;
+    index: number | null;
+  } {
+    // eslint-disable-next-line @typescript-eslint/typedef,@typescript-eslint/naming-convention
+    const [_dummy, name, index] =
```
Comment (derevnjuk) [inline packages/validator/src/humanizer/formatters/WordingHelper.ts:35]: I would prefer to use a shorter name

```suggestion
    const [_, name, index] =
```

**Review by derevnjuk — CHANGES_REQUESTED** [review]

**Review by derevnjuk — APPROVED** [review]
