### PR TITLE
fix(sampler): introduce max-length support for string pattern format sample

### LINKED ISSUE #208: Pattern string sampler does not take into account `maxLength` property
### Description

Pattern string sampler does not take into account the `maxLength` property and produce an unexpected  error

### Steps to reproduce

Pass the schema to `sample` as follows:

```js
sample({
  type: 'string',
  format: 'pattern',
  pattern: '^[A-Z0-9]*$',
  maxLength: 10});
```

### Actual result

Error reported:
```
Sample string cannot be generated by boundaries: maxLength=10, format=pattern
```

### Expected result

Sample value generated successfully

```
   RRRRR
```

### PR DESCRIPTION
**Pull request by ostridm**
closes #208

### CODE REVIEW

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ export class StringSampler implements Sampler {
       _min: number,
       _max: number,
       { pattern }: { pattern: string | RegExp }
-    ) => this.patternSample(pattern),
+    ) => this.patternSample(pattern, _max),
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:36]:
```suggestion
    ) => this.patternSample(pattern, max),
```

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 2]
```diff
@@ -47,8 +47,10 @@ export class StringSampler implements Sampler {
     return this.checkLength(sampler(min || 0, max, schema), format, min, max);
   }
 
-  private patternSample(pattern: string | RegExp): string {
+  private patternSample(pattern: string | RegExp, max: number): string {
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:50]:
```suggestion
  private patternSample(pattern: string | RegExp, max?: number): string {
```

File: packages/openapi-sampler/tests/string.spec.ts [hunk 3]
```diff
@@ -24,6 +24,33 @@ describe('StringSampler', () => {
       },
       expected: '44'
     },
+    {
```
Comment (derevnjuk) [inline packages/openapi-sampler/tests/string.spec.ts:27]: The case, where both `maxLength` and range (e.g., `{1, 20}`) are used simultaneously, is not covered.

**Review by derevnjuk — CHANGES_REQUESTED** [review]

**Review by derevnjuk — APPROVED** [review]
