### PR TITLE
fix(sampler): introduce `minLength` support for string pattern format sample

### LINKED ISSUE #216: Pattern string sampler does not take into account `minLength` property
### Description

Pattern string sampler does not take into account the `minLength` property and produce an unexpected error while string is being sampled.

### Steps to reproduce

Pass the schema to `sample` as follows:

```js
sample({
  type: 'string',
  format: 'pattern',
  maxLength: 4,
  minLength: 4,
  pattern: '^[0-9]+$'});
```

### Actual result

Error reported:
```
Sample string cannot be generated by boundaries: minLength=4, maxLength=4, format=pattern
```

### Expected result

Sample value generated successfully

```
   4444
```

### PR DESCRIPTION
**Pull request by ostridm**
closes #216

### CODE REVIEW

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 1]
```diff
@@ -47,11 +47,23 @@ export class StringSampler implements Sampler {
...
+  ): string {
     const randExp = new RandExp(pattern);
+    randExp.randInt = (a, b) => Math.floor((a + b) / 2);
+
+    if (min) {
+      randExp.max = 2 * min;
+
+      const result = randExp.gen();
+
+      return max && result.length > max ? result.substring(0, max) : result;
```
Comment (pmstss) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:63]: doesn't look clear (`result.length > max` - why not greater or equal?) and safe (truncating of generated string)  enough: e.g. for `^[a]+[b]+$` with both min/max length constraints set to 2 - currently `aa` is produced instead of `bb`.

please add code comments that will explain the details of the root cause and the workaround. test cases that are expected to be failed with that workaround are welcome.

**Review by pmstss — CHANGES_REQUESTED** [review]

**Review by pmstss — APPROVED** [review]
please avoid doing force pushes after review started in next prs
