### PR TITLE
fix(oas): combine `PathItemObject` and `OperationObject` parameters

### LINKED ISSUE #248: OAS: Converter does not pick up the `PathItemObject` parameters
### Description

Converting of specification to HAR miss the parameters residing on `PathItemObject`. 

Here it is required to improve converter to combine both `OperationObject` and `PathItemObject` parameters with precedence of operation's ones.

### Steps to reproduce

Pass the `my-schema.yaml` (see below) to the `oas2har` as follows:

```ts
import { oas2har } from '@har-sdk/oas';
import { readFile } from 'fs';
import { promisify } from 'util';
import { load } from 'js-yaml';

const content = await promisify(readFile)(
  './my-schema.yaml',
  'utf8'
);

const result = oas2har(load(content) as OpenAPIV3.Document);
```

<details>
<summary>my-schema.yaml</summary>

```
openapi: 3.0.3
info:
  title: locations
  version: '1.0'
servers:
  - url: https://brokencrystals.com
paths:
  /locations:
    parameters:
      - in: query
        name: lat
        schema:
          type: number
      - in: query
        name: lng
        schema:
          type: number
    get:
      responses:
        '200':
          description: ''
```
</details>

### Actual result

Query parameters missing:

```json
[
  {
    "bodySize": 0,
    "cookies": [],
    "headers": [],
    "headersSize": 0,
    "httpVersion": "HTTP/1.1",
    "method": "GET",
    "queryString": [],
    "url": "https://brokencrystals.com/locations"
  }
]
```

### Expected result

Conversion performed correctly, query parameters are sampled.

```json
[
  {
    "bodySize": 0,
    "cookies": [],
    "headers": [],
    "headersSize": 0,
    "httpVersion": "HTTP/1.1",
    "method": "GET",
    "queryString": [
      {
        "name": "lat",
        "value": "42"
      },
      {
        "name": "lng",
        "value": "42"
      }
    ],
    "url": "https://brokencrystals.com/locations?lat=42&lng=42"
  }
]
```

### PR DESCRIPTION
**Pull request by ostridm**
fixes #248

### CODE REVIEW

File: packages/oas/src/utils/params.ts [hunk 1]
```diff
@@ -1,17 +1,27 @@
 import type { ParameterObject } from '../types';
-import { getOperation } from './operation';
 import type { OpenAPI } from '@har-sdk/core';
 
+const isParameter = (param: unknown): param is ParameterObject =>
+  param && typeof param === 'object' && 'in' in param && 'name' in param;
```
Comment (derevnjuk) [inline packages/oas/src/utils/params.ts:5]: Validation is not the intended purpose of such functions, especially when there are no invariants except for ref objects. You have to throw an error if refs are still there at the moment of call.

File: packages/oas/src/utils/params.ts [hunk 2]
```diff
@@ -1,17 +1,27 @@
...
+
+const toParameters = (param: unknown): ParameterObject[] =>
```
Comment (derevnjuk) [inline packages/oas/src/utils/params.ts:7]: Are you casting parameters to same parameters? Unclear name

Comment (ostridm) [reply packages/oas/src/utils/params.ts]: Excluding `*.ReferenceObject` from `OpenAPI.Parameter`

**Review by derevnjuk — APPROVED** [review]
