### PR TITLE
fix(openapi-sampler): able to sample pattern with nested infinite quantifiers and max-length

### LINKED ISSUE #246: Pattern string sampler fails maxLength constraint when pattern contains nested unlimited quantifiers
### Description

Pattern string sampler fails maxLength constraint when pattern contains nested unlimited quantifiers and produce an unexpected error

### Steps to reproduce

Pass the schema to `sample` as follows:

```js
sample({
  maxLength: 55,
  minLength: 0,
  format: 'pattern',
  pattern: '^[A-Za-z0-9._%-]+@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{1,4}$',
  type: 'string'
});
```

### Actual result

Error reported:
```
Sample string cannot be generated by boundaries: minLength=0, maxLength=55, format=pattern
```

### Expected result

Sample value generated successfully

```
 gggggg@FFFFFF.FFFFFF.FFFFFF.FFFFFF.FFFFFF.FFFFFF.zz
```

### PR DESCRIPTION
**Pull request by ostridm**
closes #246

### CODE REVIEW

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 1]
```diff
@@ -55,30 +55,60 @@ export class StringSampler implements Sampler {
...
+
+    if (result.length >= min) {
+      return result;
     }
 
-    randExp.max = max ?? randExp.max;
+    // ADHOC: fallback for failed min quantifier probe with doubled min length
+
+    randExp.max = 2 * min;
     randExp.randInt = (a, b) => Math.floor((a + b) / 2);
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:109]: It's unclear why `randInt` field is assigned the same value multiple times on the same instance

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 2]
```diff
@@ -55,30 +55,60 @@ export class StringSampler implements Sampler {
...
+
+    return !!max && result.length > max && this.hasInfiniteQuantifier(pattern)
+      ? this.sampleInfiniteQuantifier(randExp, max)
+      : result;
+  }
+
+  private hasInfiniteQuantifier(pattern: string | RegExp) {
+    const pat = pattern.toString();
+
+    return ['+', '*', ',}'].some((q) => pat.includes(q));
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:74]:
```suggestion
    return /(\+|\*|\{\d*,\})/.test(pattern.toString());
```

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 3]
```diff
@@ -55,30 +55,60 @@ export class StringSampler implements Sampler {
...
+  }
+
+  private sampleInfiniteQuantifier(randExp: RandExp, max: number): string {
+    randExp.randInt = (a, b) => Math.floor((a + b) / 2);
 
-      randExp.max = 0;
-      randExp.randInt = (a, _) => a;
+    for (let i = 1, lmax = max; lmax > 0; lmax = Math.floor(max / ++i)) {
+      randExp.max = lmax;
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:81]: The loop is too complex, please streamline it as follow:

```suggestion
    for (let i = 1; i <= max; i++) {
      randExp.max = Math.floor(max / i);
```

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 4]
```diff
@@ -55,30 +55,60 @@ export class StringSampler implements Sampler {
...
+  }
 
-      randExp.max = 2 * min;
-      randExp.randInt = (a, b) => Math.floor((a + b) / 2);
+  private sampleMinLength(randExp: RandExp, min: number, max: number) {
+    // ADHOC: make a probe for regex using min quantifier value
+    // e.g. ^[a]+[b]+$ expect 'ab', ^[a-z]*$ expect ''
 
-      return this.adjustMaxLength(randExp.gen(), max);
+    randExp.max = 0;
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:97]: Try to generate with minimum length, and then if this fails, just double it

```suggestion
    randExp.max = min;
```

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 5]
```diff
@@ -55,30 +55,60 @@ export class StringSampler implements Sampler {
...
+    randExp.randInt = (a, _) => a;
+
+    const result = randExp.gen();
+
+    if (result.length >= min) {
+      return result;
     }
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:104]: Inverse the condition to avoid duplicates like this:
```ts
if (result.length < min) {
  randExp.max = 2 * min;
  result = randExp.gen();
}
```

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 6]
```diff
@@ -55,30 +55,60 @@ export class StringSampler implements Sampler {
...
       }
+    }
 
-      // ADHOC: fallback for failed min quantifier probe with doubled min length
+    return '';
+  }
 
-      randExp.max = 2 * min;
-      randExp.randInt = (a, b) => Math.floor((a + b) / 2);
+  private sampleMinLength(randExp: RandExp, min: number, max: number) {
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:93]:
```suggestion
  private sampleWithMinLength(randExp: RandExp, min: number, max: number) {
```

Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:93]: You are passing `max` as an extra arg w/o any reason; streamline the flow by calling `adjustMaxLength` only within `patternSample` method (if possible)

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 7]
```diff
@@ -55,30 +55,60 @@ export class StringSampler implements Sampler {
...
 
-      randExp.max = 0;
-      randExp.randInt = (a, _) => a;
+    for (let i = 1, lmax = max; lmax > 0; lmax = Math.floor(max / ++i)) {
+      randExp.max = lmax;
 
       const result = randExp.gen();
 
-      if (result.length >= min) {
+      if (result.length <= max) {
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:85]: Could we get in a situation when it will consistently generates strings longer than max? Seems we should add a maximum iteration limit. Let's test with some `Number.MAX_SAFE_INTEGER` and see

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 8]
```diff
@@ -55,30 +55,60 @@ export class StringSampler implements Sampler {
...
+
+    const result = randExp.gen();
+
+    return !!max && result.length > max && this.hasInfiniteQuantifier(pattern)
+      ? this.sampleInfiniteQuantifier(randExp, max)
+      : result;
+  }
+
+  private hasInfiniteQuantifier(pattern: string | RegExp) {
+    const pat = pattern.toString();
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:72]: `RegExp#toString()` and `pattern` keyword is not compatible 

```suggestion
    const pat = pattern.source;
```

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 9]
```diff
@@ -55,30 +55,60 @@ export class StringSampler implements Sampler {
     const randExp = new RandExp(pattern);
 
     if (min) {
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:57]: Use more explicit undefined checks for min and max to avoid potential issues with 0. Here is example:
```suggestion
    if (min !== undefined) {
```

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 10]
```diff
@@ -55,30 +55,60 @@ export class StringSampler implements Sampler {
...
-      // e.g. ^[a]+[b]+$ expect 'ab', ^[a-z]*$ expect ''
+      return this.sampleMinLength(randExp, min, max);
+    }
+
+    randExp.max = max ?? randExp.max;
+    randExp.randInt = (a, b) => Math.floor((a + b) / 2);
+
+    const result = randExp.gen();
+
+    return !!max && result.length > max && this.hasInfiniteQuantifier(pattern)
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:66]: ditto

**Review by derevnjuk — CHANGES_REQUESTED** [review]

File: packages/openapi-sampler/src/samplers/StringSampler.ts (hunk 6 above)
Comment (ostridm) [reply packages/openapi-sampler/src/samplers/StringSampler.ts:93]: Unfortunately, `adjustMaxLength` applied only for doubled `min` 
Just in case, applying `adjustMaxLength` to the first probe will not fail controversial cases like 

```
{
  type: 'string',
  format: 'pattern',
  pattern: '^[a]+[b]+$',
  maxLength: 1,
  minLength: 1
}
```

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 11]
```diff
@@ -107,6 +140,33 @@ export class StringSampler implements Sampler {
...
+    ];
+
+    const boundariesStr = pairs
+      .filter((p) => !this.checkBoundary(p.value))
+      .map((p) => `${p.key}=${p.value}`)
+      .join(', ');
+
+    if (boundariesStr) {
+      throw new Error(
+        `Sample string cannot be generated by boundaries: ${boundariesStr}`
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:156]: The error message is unclear
```suggestion
        `Sample string cannot be generated by boundaries: ${boundariesStr}. Both minLength and maxLength must not exceed ${this.MAX_PATTERN_SAMPLE_LENGTH}`
`
```

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 12]
```diff
@@ -107,6 +140,33 @@ export class StringSampler implements Sampler {
...
+    }
+  }
+
+  private checkBoundary(boundary?: number) {
+    return (
+      boundary === undefined ||
+      (typeof boundary === 'number' &&
+        boundary >= 0 &&
+        boundary <= this.MAX_PATTERN_SAMPLE_LENGTH)
+    );
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:167]: The check is redundant; do not validate the schema

```suggestion
    return (
      boundary === undefined ||
      boundary <= this.MAX_PATTERN_SAMPLE_LENGTH
    );
```

File: packages/openapi-sampler/src/samplers/StringSampler.ts [hunk 13]
```diff
@@ -2,6 +2,7 @@ import { Sampler, OpenAPISchema } from './Sampler';
 import RandExp from 'randexp';
 
 export class StringSampler implements Sampler {
+  private readonly MAX_PATTERN_SAMPLE_LENGTH = 500;
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/samplers/StringSampler.ts:5]: Add a code comment to explain a choice of 500

**Review by derevnjuk — APPROVED** [review]
