### PR TITLE
fix(oas): serialize binary and base64 data

### LINKED ISSUE #181: Unexpected `Content-Transfer-Encoding` header for some multipart data
### Description

Multipart form-data default parameter value `test` is treated as `base64` encoded

### Steps to reproduce

Pass the `my-schema.yaml` (see below) to the `oas2har` as follows:

```ts
import { oas2har } from '@har-sdk/oas';
import { readFile } from 'fs';
import { promisify } from 'util';
import { load } from 'js-yaml';

const content = await promisify(readFile)(
  './my-schema.yaml',
  'utf8'
);

const result = oas2har(load(content) as OpenAPIV2.Document);
```

<details>
<summary>my-schema.yaml</summary>

```
swagger: '2.0'
info:
  title: Form-data parameter test
  version: 1.0.0
host: brightsec.com
basePath: /v1
schemes:
  - https
consumes:
  - multipart/form-data
produces:
  - application/json
paths:
  /example:
    post:
      consumes:
        - multipart/form-data
      parameters:
        - name: name
          in: formData
          type: string
          required: true
          default: test
      responses:
        201:
          description: Creation success
```
</details>

### Actual result

Multipart form data  in HAR entry `postData` contains `Content-Transfer-Encoding: base64` header:

```
    "postData": {
      "mimeType": "multipart/form-data; boundary=956888039105887155673143",
      "text": "--956888039105887155673143\r\nContent-Disposition: form-data; name=\"name\"; filename=\"name\"\r\nContent-Type: application/octet-stream\r\nContent-Transfer-Encoding: base64\r\n\r\ntest\r\n--95688803910588715567314
3--"
    }
```

### Expected result

```
    "postData": {
      "mimeType": "multipart/form-data; boundary=956888039105887155673143",
      "text": "--956888039105887155673143\r\nContent-Disposition: form-data; name=\"name\"\r\n\r\ntest\r\n--956888039105887155673143--"
    }
```

### Additional info

Detection is performed by `^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)?$` regular expression, that leads to false positives for some plain strings.

### PR DESCRIPTION
**Pull request by derevnjuk**
fixes #181

### CODE REVIEW

File: packages/oas/src/utils/base64.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+const normalizeBase64 = (value: string) => encodeURIComponent(value);
```
Comment (pmstss) [inline packages/oas/src/utils/base64.ts:1]: please describe necessity / idea behind

Comment (derevnjuk) [reply packages/oas/src/utils/base64.ts:1]: Oh, thanks, I forgot to fix this implementation. It is necessary to handle utf16, For example, passing the string `✓ à la mode` to `btoa` will result in the error "DOMException [InvalidCharacterError]: Invalid character" by converting to utf8

https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem

File: packages/oas/src/converter/parts/postdata/BodyConverter.ts [hunk 2]
```diff
@@ -69,69 +73,101 @@ export abstract class BodyConverter<T extends OpenAPI.Document>
...
   }
 
+  private encodeBinary(
+    value: unknown,
+    schema?: OpenAPIV2.SchemaObject | OpenAPIV3.SchemaObject
+  ): string {
+    const encoded = this.encodeOther(value);
+
+    return this.BASE64_FORMATS.includes(schema?.format)
+      ? // FIXME: avoid double encoding?
```
Comment (derevnjuk) [inline packages/oas/src/converter/parts/postdata/BodyConverter.ts:101]: @pmstss fyi

File: packages/oas/tests/fixtures/binary-body.swagger.result.json [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+        "name": "content-type",
+        "value": "image/png"
+      }
+    ],
+    "headersSize": 0,
+    "httpVersion": "HTTP/1.1",
+    "method": "POST",
+    "postData": {
+      "mimeType": "image/png",
+      "text": "wolQTkcNChoK"
```
Comment (pmstss) [inline packages/oas/tests/fixtures/binary-body.swagger.result.json:35]: isn't it expected to be 'iVBORw0KGgo='?

File: packages/oas/tests/fixtures/binary-body.swagger.result.json [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+        "name": "content-type",
+        "value": "multipart/form-data"
+      }
+    ],
+    "headersSize": 0,
+    "httpVersion": "HTTP/1.1",
+    "method": "POST",
+    "postData": {
+      "mimeType": "multipart/form-data; boundary=956888039105887155673143",
+      "text": "--956888039105887155673143\r\nContent-Disposition: form-data; name=\"base64\"\r\n\r\nlorem\r\n--956888039105887155673143\r\nContent-Disposition: form-data; name=\"binary\"\r\n\r\nlorem\r\n--956888039105887155673143\r\nContent-Disposition: form-data; name=\"byte\"\r\n\r\nlorem\r\n--956888039105887155673143--"
```
Comment (pmstss) [inline packages/oas/tests/fixtures/binary-body.swagger.result.json:73]: is "lorem" expected here in all three parts?

Comment (derevnjuk) [reply packages/oas/tests/fixtures/binary-body.swagger.result.json:73]: Yeah, Swagger does not allow specifying the `format` for the `file` parameters. It will be treated as a plain string. It is possible to use an extension (i.e. `x-format`), but we does not support it yet

File: packages/oas/tests/fixtures/binary-body.swagger.result.json (hunk 3 above)
Comment (pmstss) [reply packages/oas/tests/fixtures/binary-body.swagger.result.json]: adjusted

**Review by pmstss — APPROVED** [review]
