### PR TITLE
fix(openapi-sampler): deterministic output

### LINKED ISSUE #83: make openapi-sampler deterministic again
Currently samplers produce random faker based data. It adds unwanted faker dependency and make the result non-deterministic.

### PR DESCRIPTION
**Pull request by pmstss**
fixes #83

### CODE REVIEW

File: packages/openapi-sampler/src/utils.ts [hunk 1]
```diff
@@ -76,3 +21,5 @@ export const mergeDeep = (
     },
     Array.isArray(objects[objects.length - 1]) ? [] : {}
   );
+
+export const randomArrayElement = <T>(x: T[]): T | undefined => x[0];
```
Comment (derevnjuk) [inline packages/openapi-sampler/src/utils.ts:25]:
```suggestion
export const firstArrayElement = <T>(x: T[]): T | undefined => x[0];
```

**Review by derevnjuk — APPROVED** [review]

**Comment by pmstss** [comment]
@derevnjuk any ideas what to do with codeclimate - which seems is still busy with #72:

<details>

image
</details>

**Comment by derevnjuk** [comment]
@pmstss I don't have any idea. I have tried to apply a workaround (https://docs.codeclimate.com/docs/fixing-branches-and-pull-requests#instructions-for-rebasing), but there is no success. Let's write to support.
