### PR TITLE
fix(*): use stricter type prechecks

### LINKED ISSUE #115: Use stricter type prechecks
**Actual behavior**: 
* `mimeTypes.map is not a function` for non-array consumes value
* `x.trim is not a function` for non-string oas document title
* `x.trim is not a function` for non-string swagger host

**Expected behavior**: no exception

### PR DESCRIPTION
**Pull request by derevnjuk**
closes #115

### CODE REVIEW

File: packages/core/src/importers/BaseOASImporter.ts [hunk 1]
```diff
@@ -17,8 +17,13 @@ export abstract class BaseOASImporter<
     doc: OpenAPI.Document;
     format: DocFormat;
   }): string {
```
Comment (pmstss) [inline packages/core/src/importers/BaseOASImporter.ts:19]:
```suggestion
  }): string | undefined {
```

File: packages/oas/src/converter/DefaultConverter.ts [hunk 2]
```diff
@@ -351,20 +352,14 @@ export class DefaultConverter implements Converter {
...
-      return queryStrings;
-    }
-
-    for (const param of pathObj.parameters) {
-      if (
-        typeof param.in !== 'undefined' &&
-        param.in.toLowerCase() === 'query'
-      ) {
+    for (const param of params) {
+      if (typeof param.in === 'string' && param.in.toLowerCase() === 'query') {
```
Comment (pmstss) [inline packages/oas/src/converter/DefaultConverter.ts:358]: are we going to ensure here (and in similar places) that `param` is not e. g. `null`?

Comment (derevnjuk) [reply packages/oas/src/converter/DefaultConverter.ts:358]: Nope, it looks odd. I don't think they have sense here.

**Review by pmstss — APPROVED** [review]
